"""add_sent_reminders_table

Revision ID: 7a957647bcc8
Revises: 1c4e4cf3d1ae
Create Date: 2026-03-06 22:28:29.337782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a957647bcc8'
down_revision: Union[str, None] = '1c4e4cf3d1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_reminders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reminder_type', sa.Enum('APPOINTMENT_24H', 'LEAD_FOLLOWUP_DAY3', 'LEAD_FOLLOWUP_DAY7', name='remindertype'), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'FAILED', 'CANCELLED', name='reminderstatus'), nullable=False),
    sa.Column('message_sent', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('error_detail', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reminder_type', 'reference_id', 'attempt', name='uq_reminder_type_ref_attempt')
    )
    op.create_index(op.f('ix_sent_reminders_phone'), 'sent_reminders', ['phone'], unique=False)
    op.create_index(op.f('ix_sent_reminders_reference_id'), 'sent_reminders', ['reference_id'], unique=False)
    op.create_index(op.f('ix_sent_reminders_reminder_type'), 'sent_reminders', ['reminder_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sent_reminders_reminder_type'), table_name='sent_reminders')
    op.drop_index(op.f('ix_sent_reminders_reference_id'), table_name='sent_reminders')
    op.drop_index(op.f('ix_sent_reminders_phone'), table_name='sent_reminders')
    op.drop_table('sent_reminders')
    # ### end Alembic commands ###
